### ISSUE TITLE
Task #2 & #3

### ISSUE THREAD

**Issue by learp** [malinink/LaravelTestWeb15#60]
2 задание и 3, все в одном pull request. Ничего страшного? или лучше так не делать?

**Comment by malinink** [comment]
Здравствуйте, конечно лучше бы разнести, мне так намного сложней проверять

**Comment by malinink** [comment]
@learp Хотя, посмотрел, у вас две миграции, пусть будет так, но всем кто ещё не сделал - делать двумя PR!
